name: ThePitLite
version: '${version}'
main: com.mc.gaul.thepitcore.ThePitLite
api-version: 1.16
depend: [ DecentHolograms, Citizens ]

commands:
  thepit:
    aliases:
      - 더핏
      - 더피트
    description: "Main command."